# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamershub_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamershubproducts',
            options={},
        ),
    ]
