# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamershub_products', '0002_auto_20171124_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamershubproducts',
            options={'verbose_name_plural': 'Gamers Hub Products'},
        ),
    ]
