# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='users/profile_images/%d/%m/%Y'),
        ),
    ]
