# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fave_game',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
