# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171102_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
