# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171102_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fave_game',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
