# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=40)),
                ('post_slug', models.SlugField(unique=True, unique_for_date='publish')),
                ('post_body', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_status', models.CharField(choices=[('save_draft', 'Draft'), ('published', 'Published')], max_length=10)),
                ('post_images', models.ImageField(blank=True, height_field='image_height', upload_to='users/blog_post_images/%d/%m/%Y', width_field='image_width')),
                ('post_views', models.IntegerField(default=0)),
                ('post_tags', models.CharField(blank=True, max_length=30, null=True)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
