# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=40)),
                ('post_slug', models.SlugField(max_length=40, unique=True)),
                ('post_body', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('post_images', models.ImageField(blank=True, height_field='image_height', upload_to='users/blog_post_images/%d/%m/%Y', width_field='image_width')),
                ('post_views', models.IntegerField(default=0)),
                ('post_tags', models.CharField(blank=True, max_length=30, null=True)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
