# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamersblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_slug',
            field=models.SlugField(unique_for_date='publish'),
        ),
    ]
