# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamersblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_slug',
            new_name='slug',
        ),
    ]
