# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamersblog', '0002_auto_20171011_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-publish',)},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='published_date',
            new_name='publish',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
