# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamersblog', '0004_auto_20171011_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_slug',
            field=models.SlugField(unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_title',
            field=models.CharField(max_length=40),
        ),
    ]
