# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamersblog', '0005_auto_20171012_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_views',
            field=models.IntegerField(default=0),
        ),
    ]
