# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers_blog', '0003_auto_20171011_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_status',
            field=models.CharField(choices=[('save_draft', 'Draft'), ('published', 'Published')], max_length=10),
        ),
    ]
